name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to EB
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      EB_APPLICATION_NAME: lightweight-ml-serving-api
      EB_ENVIRONMENT_NAME: ${EB_APPLICATION_NAME}-env
      S3_BUCKET: ${EB_APPLICATION_NAME}-deployment-bucket
      ZIP_FILE: app.zip

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Generate version label
        id: vars
        run: |
          echo "VERSION_LABEL=v-${{ github.run_number }}-$(date +%s)" >> $GITHUB_ENV
          echo "ZIP_FILE=deploy-${{ github.run_number }}.zip" >> $GITHUB_ENV

      - name: Package application
        run: |
          zip -r $ZIP_FILE .

      - name: Upload to S3
        run: |
          aws s3 cp $ZIP_FILE s3://$S3_BUCKET/$ZIP_FILE

      - name: Create new EB application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name $EB_APPLICATION_NAME \
            --version-label $VERSION_LABEL \
            --source-bundle S3Bucket="$S3_BUCKET",S3Key="$ZIP_FILE" \
            --auto-create-application

      - name: Deploy to EB environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name $EB_ENVIRONMENT_NAME \
            --version-label $VERSION_LABEL

